import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar/Navbar'
import { cartSVG, newCartSVG } from './icons/icons'
import Link from 'next/link'

const inter = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", '800', "900"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 w-screen h-screen flex flex-col`}>
        <Navbar />
        <div className='flex-1 h-full overflow-hidden'>
          {children}
        </div>
        <Link href="/cart" className='absolute bottom-8 right-8 w-16 h-16 fill-white z-40 rounded-full bg-slate-900 flex justify-center items-center'>
          {newCartSVG}
        </Link>
      </body>
    </html>
  )
}
