import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar/Navbar'

const inter = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", '800', "900"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 w-screen h-screen flex flex-col`}>
        <Navbar />
        <div className='flex-1 h-full overflow-hidden'>
          {children}
        </div>
      </body>
    </html>
  )
}
